### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Roj13** [nicolasgarnier/drive-music-player#16]
For some reason the time that is suppose to be total length of the song seems to be showing the song current time at playing

**Comment by ManuelGuillen19** [comment]
fix bug

**Comment by ManuelGuillen19** [comment]
sorry, an error ,,,

**Comment by nicolasgarnier** [comment]
Yes confirmed. this is because of a bug in Google Drive file serving. Chrome is not affected but some other browsers are (IE and Firefox at least). I;ve let the Google Drive team know about this bug. Please follow #31 for updates.

**Comment by nicolasgarnier** [comment]
And thanks for the repport!
