### ISSUE TITLE
Long filename, player window is too narrow to see entire filename

### ISSUE THREAD

**Issue by beboparubop** [nicolasgarnier/drive-music-player#22]
This makes it impossible to select which files on a playlist I want to play.

See attached jpg
![music player for google drive_ playlist](https://cloud.githubusercontent.com/assets/10201437/5445550/a69e326e-8469-11e4-908f-deb3e8045f2b.png)

Thanks!

**Comment by nicolasgarnier** [comment]
+1 lets keep track of this on #13
