### ISSUE TITLE
Driveplayer does not work on Android Chrome

### ISSUE THREAD

**Issue by RJPK** [nicolasgarnier/drive-music-player#34]
Google's Driveplayer works perfect in Chrome OS or Chrome, but not on Android Chrome. It simply doesn't do what is has to do: play the songs. It shows them but does not play them. Sometimes the time of a song shows 00:00 and does not play, sometimes the time of a song shows the exact time but does not play either. Like in this screenshot: the first title is about 10 minutes, but is shows 00:00. The next song shows the time correct, but is doesn't play. In Chrome OS this list plays perfect!

![screenshot_2015-01-24-12-26-04](https://cloud.githubusercontent.com/assets/10683302/5887245/fe38645c-a3c4-11e4-9079-0c826f438b8e.png)

**Comment by nicolasgarnier** [comment]
I fixed this issue a couple days ago. Please try again and sorry about that!
