### ISSUE TITLE
Google Drive Music Player

### ISSUE THREAD

**Issue by tylermgrams** [nicolasgarnier/drive-music-player#40]
The bar that is supposed to be able to be clicked in order to jump or revert to a specific time of an audio file is not functional so in order to replay a segment I have to completely restart the entire audio and just wait for the it to get back to the time I needed to listen to.
![time bar problem](https://cloud.githubusercontent.com/assets/10996972/6193010/62a1ca4e-b385-11e4-8b72-245f28aa3935.png)

**Comment by juniorsatanas** [comment]
You are using which browser?

**Comment by nicolasgarnier** [comment]
short story long: it's because of a bug in Google Drive. Please see issue #31 we'll update this bug :)
