### ISSUE TITLE
Drag & Drop an item is buggy

### ISSUE THREAD

**Issue by oldanderw** [nicolasgarnier/drive-music-player#48]
when moving a track up or down, the track that can be seen moves to the top of the screen but an empty still is there where the track should be.
![bug](https://cloud.githubusercontent.com/assets/481549/6924122/363f5258-d7a4-11e4-93cc-da694ef862e5.png)

**Comment by nicolasgarnier** [comment]
I confirm: this happens when we are scrolled down the page.

**Comment by oldanderw** [comment]
thank you

**Comment by nicolasgarnier** [comment]
Fixed!
