### ISSUE TITLE
Drive Player for the Android

### ISSUE THREAD

**Issue by eaesch** [nicolasgarnier/drive-music-player#52]
Hi Nicolas,  This is NOT a problem. You have a fantastic product. I have stage 4 cancer and wish to share Christian music that has inspired me and which may help others. Do you have a product that will play Google Drive music on the Android?

God Bless,
Ed Aeschlimann
edaeschlimann@gmail.com
904-422-0747

**Comment by nicolasgarnier** [comment]
Hey @eaesch,

I've fixed a bug 2 days ago and the player should now work on Android.

Cheers!

**Comment by eaesch** [comment]
Wonderful news.
Thank h you so much.
Ed
