### ISSUE TITLE
You are not authorized to read this file or the file does not exist

### ISSUE THREAD

**Issue by eaesch** [nicolasgarnier/drive-music-player#53]
I have 22 songs in a shared folder and when I log into a different account and select the same drive folder I get this message at the bottom many times. I have no other non-music files in the shared folder.

**Comment by nicolasgarnier** [comment]
Hey @eaesch,
The way the permissions work for Google Drive is that you have to "open" these files with your new account via Google Drive (right Click > Open-with) or via the "Add audio files from Google Drive" Widget inside the app (which is provided by Google). As you've noticed sharing the files with a new account and opening the same URL won't work unfortunately...
