### ISSUE TITLE
Random Refresh

### ISSUE THREAD

**Issue by sampellino** [nicolasgarnier/drive-music-player#67]
Randomly when listening to music for a bit, the page will refresh and all of my songs in the current queue are gone. When I reload my playlist, it restarts the song I left off on.

Ubuntu 15.04, Chome 43.0.2357.81 (64-bit).

I have two Google accounts if that is of any concern (one work, one personal). I have some Gmail tabs open for work, and other tabs (like drive music player) open with my personal account.

Side note - love the app!

**Comment by sampellino** [comment]
This issue seems to be resolved after your latest commit.

**Comment by sampellino** [comment]
^ Scratch that, it now refreshes randomly and asks which Google account I'd like to use

**Comment by nicolasgarnier** [comment]
So now at least when it refreshes your songs should not be gone (that was a bug). :D
Although I'm interested in this random refresh bug. Do you have any idea when it seems to happen? After 10 minutes? or 60 minutes? or really randomly?
(I'm asking because we need to refresh the auth-token after 60min)

**Comment by nicolasgarnier** [comment]
if that's it it shouldn't ask you again to choose the account though, that may be the bug...

**Comment by nicolasgarnier** [comment]
I checked the code again and it seems we'll refresh the tokens every 50 min. There is a bug where we don't use the userId when doing that. However normally this wouldn't refresh the whole page and be done in the background... so maybe a different bug is triggering your refreshes.

**Comment by nicolasgarnier** [comment]
I'm pushing this bug fix. Finger crossed :D

**Comment by nicolasgarnier** [comment]
Let me know if this happens again for you.

**Comment by sampellino** [comment]
Will do @nicolasgarnier ! I use DrivePlayer daily while I code at work :)

I figured it had something to do with Auth Tokens expiring or something. I'm headed out for the day - but I'll start DrivePlayer tomorrow when I come into the office, and I'll start a timer to see how long it takes to refresh (if it does anymore).

**Comment by nicolasgarnier** [comment]
No news good news? :smiley: (or not?)

**Comment by sampellino** [comment]
Sorry! I caught the flu shortly after writing my last comment.

Still getting the random refresh, so I'll time it today or tomorrow and let you know how long it takes. In the meantime - I have found that it is independent of interactivity with the app (as one time, it happened to me about 30 seconds after clicking "next").

**Comment by nicolasgarnier** [comment]
Oh do you use Playlists? Because in case of unknown errors I just reload the page: https://github.com/nicolasgarnier/drive-music-player/blob/master/js/dmp.playlist.js#L92

I'm going to start tracking what these errors are in Google Analytics to get a better picture.

**Comment by sampellino** [comment]
Sorry for the lack of communication @nicolasgarnier . Yes, I access DrivePlayer via a bookmark of my office playlist. I don't think I've had it randomly refresh in a while - I think you can close this ticket for now, and I'll let you know if it happens again.

**Comment by nicolasgarnier** [comment]
Good to hear! Please let me know if this happens again!

Cheers!
