### ISSUE TITLE
Music player not working

### ISSUE THREAD

**Issue by brazil10** [nicolasgarnier/drive-music-player#68]
The google music player on the chrome book wouldnt work

**Comment by nicolasgarnier** [comment]
It should work fine on Chromebook. Could you try again and make sure you have a fast internet connect please?

**Comment by brazil10** [comment]
Thanks

*Hifza Da Silva Santos Junior*

On 25 June 2015 at 22:43, Nicolas Garnier <notifications@github.com> wrote:

> It should work fine on Chromebook. Could you try again and make sure you
> have a fast internet connect please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolasgarnier/drive-music-player/issues/68#issuecomment-115406552>
> .
>

-- 
This email and its attachments may be confidential and are intended solely 
for the use of the individual to whom it is addressed. Any views or 
opinions expressed are solely those of the author and do not necessarily 
represent those of University Academy Keighely. If you are not the intended 
recipient of this email and its attachments, you must take no action based 
upon them, nor must you copy or show them to anyone. Please contact the 
sender if you believe you have received this email in error.
