### ISSUE TITLE
Need a button "Play next track"

### ISSUE THREAD

**Issue by bsver** [nicolasgarnier/drive-music-player#71]
Hi! I really like your music player and it saved my life at work. But I feel a strong need to have an extra button "Play next song". Because whenever i don't want to listen to the current song any longer, I have to go and search through the whole list of songs and find the song that is playing at the moment and then turn on the next song manually. It's rather inconvenient. Please add the button to the player. If the  shuffle on is activated, the button should turn on the next random song. Thanks.

**Comment by sampellino** [comment]
:+1: 

Would love to see this

**Comment by nicolasgarnier** [comment]
Done! UI Refresh deployed :)

FYI there is also a keyboard shortcut (right arrow)
