### ISSUE TITLE
Right-arrow not working with shuffle

### ISSUE THREAD

**Issue by sampellino** [nicolasgarnier/drive-music-player#72]
When shuffle is turned on and the right arrow key is pressed, the player goes to the next sequential song in the list instead of jumping to a random song.

**Comment by sampellino** [comment]
I saw this comment in `js/dmp.player.js` while reviewing your latest commit

```
// If we are not looping on the same song we find the next song's ID or if the event is from a keydown.
  if (!($(".jp-repeat-one").is(":visible")) || (e && e.type == "keydown")) {
    if ((e && e.type != "keydown") && $(".jp-shuffle").is(":visible")) {
      // In the case of shuffle (but not when using arrows to browse) we choose a random song.
      playingIndex = Math.floor(Math.random()*dmp.playlist.getAudioList().length);
    } else {
        ...
```

Could you give some insight as to why right arrow key should not choose a random song when shuffle is enabled? Every media player I've used will shuffle with the "next song" keyboard shortcut, and I can't see a reason why it should just go to the next song in the list.

**Comment by nicolasgarnier** [comment]
Yes somehow I specifically bypassed shuffle on purpose when using the keyboard shortcut. Not sure why actually I don't remember what went through my mind back then :D

I'll revert that since it doesn't make much sense really (and all other players I've tried behvaes like that)

**Comment by nicolasgarnier** [comment]
Deployed!

**Comment by sampellino** [comment]
Awesome, works perfectly now!
