### ISSUE TITLE
does not play .webm files

### ISSUE THREAD

**Issue by pleabargain** [nicolasgarnier/drive-music-player#75]
Hi 
I just tested playing .webm files.
No joy.

I made the webm file with
Screencastify (Screen Video Recorder) 1.6.5

![screenshot from 2015-06-30 15 28 43](https://cloud.githubusercontent.com/assets/640846/8430774/c24848c4-1f3c-11e5-97ab-5fac52aec143.png)

**Comment by nicolasgarnier** [comment]
could you maybe attach the webm audio file here or share it with nivco.las@gmail.com so that I could experiment with it? I'm having issues finding a webm audio only file :D for testing

**Comment by nicolasgarnier** [comment]
Forget it, I've found the bug. Will push the fix soon.

**Comment by nicolasgarnier** [comment]
Should be fixed now!
